// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReportSystem.Data;

#nullable disable

namespace ReportSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260616114013_AddViolatorAndScores")]
    partial class AddViolatorAndScores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReportSystem.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeverityLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Списывание на экзамене",
                            Name = "Списывание",
                            SeverityLevel = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Травля",
                            Name = "Буллинг",
                            SeverityLevel = 3
                        },
                        new
                        {
                            Id = 3,
                            Description = "Пропуск занятий",
                            Name = "Прогулы",
                            SeverityLevel = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Нарушение порядка",
                            Name = "Хулиганство",
                            SeverityLevel = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Иные нарушения",
                            Name = "Другое",
                            SeverityLevel = 1
                        });
                });

            modelBuilder.Entity("ReportSystem.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("ModeratorComment")
                        .HasColumnType("text");

                    b.Property<int>("ReliabilityScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("ViolatorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("StatusId");

                    b.HasIndex("ViolatorId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ReportSystem.Models.ReportStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReportStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ожидает приговора"
                        },
                        new
                        {
                            Id = 2,
                            Name = "В разработке"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Виновен (Принято)"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Оправдан (Отклонено)"
                        });
                });

            modelBuilder.Entity("ReportSystem.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("ReportSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Администратор Системы",
                            Login = "admin",
                            PasswordHash = "$2a$11$j5g3HarcNfrPE9lb.WTjVeLnA3eCrihb.6WL9HDKB.uuvDR4yYvtS",
                            RoleId = 1,
                            Score = 0
                        });
                });

            modelBuilder.Entity("ReportSystem.Models.Report", b =>
                {
                    b.HasOne("ReportSystem.Models.User", "Author")
                        .WithMany("Reports")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportSystem.Models.Category", "Category")
                        .WithMany("Reports")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportSystem.Models.User", "ReviewedBy")
                        .WithMany("ReviewedReports")
                        .HasForeignKey("ReviewedById");

                    b.HasOne("ReportSystem.Models.ReportStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportSystem.Models.User", "Violator")
                        .WithMany("Violations")
                        .HasForeignKey("ViolatorId");

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("ReviewedBy");

                    b.Navigation("Status");

                    b.Navigation("Violator");
                });

            modelBuilder.Entity("ReportSystem.Models.User", b =>
                {
                    b.HasOne("ReportSystem.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ReportSystem.Models.Category", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("ReportSystem.Models.User", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("ReviewedReports");

                    b.Navigation("Violations");
                });
#pragma warning restore 612, 618
        }
    }
}
